"""
ProfFinder — A6: Cold Mail Drafter Agent
Generates <200-word cold emails using GPT-4o. Triggered manually by user.
NEVER sends email — user copies and sends manually.
"""

import json
from openai import AsyncOpenAI
from app.config import get_settings
from app.models.schemas import MailDraftRequest, MailDraftResponse
from app.prompts.templates import COLD_EMAIL_PROMPT


async def draft_cold_email(request: MailDraftRequest) -> MailDraftResponse:
    """
    A6 — Cold Mail Drafter.
    Generates a personalized, paper-specific cold email.
    Uses GPT-4o for high-quality natural language output.
    """
    settings = get_settings()
    client = AsyncOpenAI(api_key=settings.openai_api_key)

    # Format selected papers
    papers_text = ""
    for i, title in enumerate(request.selected_paper_titles):
        abstract = request.selected_paper_abstracts[i] if i < len(request.selected_paper_abstracts) else ""
        papers_text += f"\nPaper {i + 1}: \"{title}\"\n"
        if abstract:
            papers_text += f"Abstract: {abstract[:300]}\n"

    prompt = COLD_EMAIL_PROMPT.format(
        degree_type=request.degree_type.value,
        professor_name=request.professor_name,
        department=request.department,
        university=request.university,
        intake_session=request.intake_session,
        selected_papers=papers_text,
        student_research_summary=request.student_research_summary[:500],
        strongest_publication=request.strongest_publication or "No formal publication yet",
    )

    response = await client.chat.completions.create(
        model=settings.openai_reasoning_model,  # GPT-4o for email drafting
        messages=[
            {
                "role": "system",
                "content": (
                    "You are an expert academic email writer. Write naturally and specifically. "
                    "The email must feel like it was written by a real person, not generated by AI. "
                    "Return valid JSON only."
                ),
            },
            {"role": "user", "content": prompt}
        ],
        response_format={"type": "json_object"},
        temperature=0.7,  # Slightly creative for natural language
    )

    result = json.loads(response.choices[0].message.content)

    return MailDraftResponse(
        subject=result.get("subject", f"Prospective {request.degree_type.value} Student — {request.intake_session}"),
        body=result.get("body", ""),
        word_count=int(result.get("word_count", len(result.get("body", "").split()))),
        professor_name=request.professor_name,
        referenced_papers=request.selected_paper_titles,
    )
